# AULA 15 - Noções de Numpy
## Algoritmos e Estrutura de Dados I

In [1]:
#importando o NumPy
import numpy as np

In [6]:
#verificando a versão do numpy
np.__version__

'1.26.4'

In [ ]:
# Para instalação de uma versão exata de um pacote Python
# !pip install numpy==1.21.5

### Criando Arrays Numpy

In [7]:
#Criando um Array a partir de uma lista Python
array1 = np.array([2, 5, 10, 34, 23, 9, 73, 21, 6])

In [8]:
print(array1) # não é separado por vírgulas e uma lista sim

[ 2  5 10 34 23  9 73 21  6]


In [9]:
#Conformando o tipo de dados do array criado
type(array1)

numpy.ndarray

In [11]:
#ndarray - n dimensional array - array de dimensão n


#Vamos ver o formato (shape) desse array
array1.shape

(9,)

In [ ]:
# Os arrays são estruturas de dados muito mais eficientes do que os tipos básicos da linguagem Python.

### Indexação em Arrays NumPy

In [27]:
print(array1)

[200   5  10  34  23   9  73  21   6]


In [13]:
array1[5]

9

In [26]:
# A indexação inicia com ZERO.

# Também posso fazer o fatiamento:
array1[1:4]

array([ 5, 10, 34])

In [25]:
# criando uma lista de índices
indices = [1, 3, 6, 8]

In [24]:
# Imprimindo os lementos com os respectivos índices:
array1[indices]

array([ 5, 34, 73,  6])

In [17]:
# Criando uma máscara (no caso vamos criar uma máscara booleana para os elementos pares)
mascara = (array1 % 2 == 0)

In [23]:
# Vamos ver a máscara criada...
mascara

array([ True, False,  True,  True, False, False, False, False,  True])

In [19]:
# Vamos utilizar a máscara criada como indexador. No caso, ele vai retornar os elementos cujos índices forem verdadeiros.
# Ou seja... vai retornar todos os valore que são pares.
array1[mascara]

array([ 2, 10, 34,  6])

In [21]:
# Utilizamos a indexação também para fazer a substituição de valores...
array1[0] = 200

In [22]:
array1

array([200,   5,  10,  34,  23,   9,  73,  21,   6])

In [ ]:
# Atenção!!!
# Não é possível incluir elementos de outros tipos de dados.
# Arrays NumPy são todos do mesmo tipo de dado.

### Funções NumPy

In [28]:
# A função array() cria um array NumPy
array2 = np.array([1,2,3,4,5])

In [29]:
print(array2)

[1 2 3 4 5]


In [30]:
array2.shape

(5,)

In [31]:
# array2 agora é um objeto do tipo nd.array... e portanto possuem uma série de métodos associados a este objeto.
# para visualizar os métodos... digite o nome... ponto... e tecle tab.
array2

array([1, 2, 3, 4, 5])

In [32]:
#Usando os métodos do array NumPy...
#cumsum --> soma acumulada
array2.cumsum()

array([ 1,  3,  6, 10, 15])

In [33]:
#cumprod --> produto acumulado
array2.cumprod()

array([  1,   2,   6,  24, 120])

In [ ]:
# Para verificar as funções disponíveis em NumPy... digite o alias (np) seguido de ponto e tab.
np

In [34]:
# Função arange --> cria um array NumPy contendo uma progressão aritmética a partir de um intervalo: inicio, fim, passo.
array3 = np.arange(0, 40, 4) 

In [36]:
array3

array([ 0,  4,  8, 12, 16, 20, 24, 28, 32, 36])

In [37]:
# Criar um array preenchido com zeros
array4 = np.zeros(7)

In [38]:
array4

array([0., 0., 0., 0., 0., 0., 0.])

In [44]:
# Criar uma matriz diagonal... 1 nas posições em diagonal e zero nas demais posições
array5 = np.eye(5)

In [45]:
print(array5)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [41]:
# Podemos passar como parâmetro um array numpy para que o mesmo seja utilizado como diagonal...
array6 = np.diag(np.array([1,2,3,4]))

In [42]:
print(array6)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


In [46]:
# Criação de um array numpy de valores booleanos
array7 = np.array([True, False, False, True])

In [47]:
print(array7)

[ True False False  True]


In [48]:
# Criação de um array numpy de strings
array8 = np.array(['pyPRO', 'Python', 'Profissional'])

In [49]:
print(array8)

['pyPRO' 'Python' 'Profissional']


A função linspace() do NumPy é usada para criar uma sequência de números igualmente espaçados dentro de um intervalo especificado. Igualmente distribuidos no intervalo especificado.  Quando você não especificar a quantidade de números a ser gerado, o padrão é gerar 50 números no intervalo.

In [50]:
print(np.linspace(0, 10)) #espaçamento linear

[ 0.          0.20408163  0.40816327  0.6122449   0.81632653  1.02040816
  1.2244898   1.42857143  1.63265306  1.83673469  2.04081633  2.24489796
  2.44897959  2.65306122  2.85714286  3.06122449  3.26530612  3.46938776
  3.67346939  3.87755102  4.08163265  4.28571429  4.48979592  4.69387755
  4.89795918  5.10204082  5.30612245  5.51020408  5.71428571  5.91836735
  6.12244898  6.32653061  6.53061224  6.73469388  6.93877551  7.14285714
  7.34693878  7.55102041  7.75510204  7.95918367  8.16326531  8.36734694
  8.57142857  8.7755102   8.97959184  9.18367347  9.3877551   9.59183673
  9.79591837 10.        ]


In [52]:
print(np.linspace(0, 10, 15))

[ 0.          0.71428571  1.42857143  2.14285714  2.85714286  3.57142857
  4.28571429  5.          5.71428571  6.42857143  7.14285714  7.85714286
  8.57142857  9.28571429 10.        ]


Muito útil para inicializar uma matriz de pesos, em uma rede neural.

A função logspace() é semelhante, só que cria uma sequencia de números espaçados logaritmicamente, dentro de um intervalo especificado.

In [ ]:
print(np.logspace(0, 10, 15))

### Manipulação de Matrizes com NumPy

In [59]:
# Criando uma matriz com listas Python
array9 = np.array([[1,2,3],[4,5,6]])

In [60]:
type(array9)

numpy.ndarray

In [61]:
print(array9)

[[1 2 3]
 [4 5 6]]


In [62]:
print(array9.shape)

(2, 3)


In [63]:
# Criando uma matriz preenchida com "1"
array10 = np.ones((2,3))

In [64]:
print(array10)

[[1. 1. 1.]
 [1. 1. 1.]]


In [65]:
print(array10.shape)

(2, 3)


In [71]:
# Criando uma matriz a partir de uma lista de listas....
# Primeiro: vamos criar uma lista de listas
lista = [[1,2,3], [4,5,6], [7,8,9]]

# Em seguida, passamos como parãmetro essa lista de listas para a função matrix
array11 = np.matrix(lista)

In [75]:
print(array11)
lista

[[1 2 3]
 [4 5 6]
 [7 8 9]]


[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [76]:
print(array11.shape)

(3, 3)


In [77]:
type(array11)

numpy.matrix

In [78]:
# Tamanho da matriz
array11.size

9

In [79]:
# Verificando o tipo de dado
print(array11.dtype)

int32


In [80]:
# Indexação em matrizes
print(array11)

# Vamos retornar apenas o elemento 2, 1 (terceira linha e segunda coluna)
print(array11[2, 1])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
8


In [81]:
# Retornando um range de números...
print(array11[0:2, 2])

[[3]
 [6]]


In [86]:
# Também posso, por exclusão, retornar todos os elementos daquela dimensão.
# Exemplo: retornar todos os elementos da linha 2 (índice 1)
print(array11[1,])

[[200   5   6]]


In [83]:
# Para alterar um elemento de uma matriz... 
array11[1,0] = 200

In [84]:
print(array11)

[[  1   2   3]
 [200   5   6]
 [  7   8   9]]


In [89]:
# Caso não haja a definição de um tipo de dados, o NumPy vai fazer uma inferência com os dados e assim associar um tipo
# mais próximo do tipo de dado.
x = np.array([1,2])   # vai decidir para um tipo inteiro
y = np.array([1.0, 2.0])  # vai decidir para um tipo float
z = np.array([1,2], dtype = np.float64)  # estamos forçando o numpy a associar o tipo float aqui.

In [90]:
print(x.dtype, y.dtype, z.dtype)

int32 float64 float64


Para verificar o número de bytes de ocupação de um array na memória utilizamos o atributo itemsize. O total de bytes, você pode consultar com nbytes. E o número de dimensões é conseguido com o atributo: ndim

In [91]:
array11.itemsize


4

In [95]:
print(array11)
array11.nbytes

[[  1   2   3]
 [200   5   6]
 [  7   8   9]]


36

In [93]:
array11.ndim

2

### Estatística Básica com NumPy

In [96]:
array15 = np.array([1, 23, 45, 12, 56, 87])

In [97]:
# Em estatística, média é uma medida de tendência central que representa o valor central de um conjunto de dados.
print(np.mean(array15))

37.333333333333336


Em probabilidade, o desvio padrão ou desvio padrão populacional é uma medida de dispersão em torno da média populacional de uma variável aleatória. O termo possui também uma acepção específica no campo da estatística, na qual também é chamado de desvio padrão amostral  e indica uma medida de dispersão dos dados em torno de média amostral. Um baixo desvio padrão indica que os pontos dos dados tendem a estar próximos da média ou do valor esperado. Um alto desvio padrão indica que os pontos dos dados estão espalhados por uma ampla gama de valores. 
O desvio padrão é amplamente utilizado em ciência de dados para avaliar a consistência dos dados e comparar conjuntos de dados diferentes.

In [98]:
# Desvio Padrão (standard desviation )
print(np.std(array15))

28.986586936412888


Variância é uma medida estatística que quantifica dos valores em um conjunto de dados em relação à média. Indica "o quão longe" em geral os seus valores se encontram do valor esperado.  O desvio padrão pode ser influenciado por valores extremos (outliers).

In [99]:
# Cálculo da variância
print(np.var(array15))

840.2222222222223


Note que o valor da variância não se encontra na mesma "medida" do desvio padrão e das amostras. É utilizado para calcular matriz de covariância e coeficiente de correlação.

### Operações Matemáticas utilizando Arrays NumPy

In [100]:
array16 = np.arange(1, 10)

In [101]:
print(array16)

[1 2 3 4 5 6 7 8 9]


In [102]:
# Soma os elementos de um array
print(np.sum(array16))

45


In [103]:
# Calcula o produto dos elementos de um array
print(np.prod(array16))

362880


In [104]:
# Soma acumulado dos elementos de um array
print(np.cumsum(array16))

[ 1  3  6 10 15 21 28 36 45]


In [105]:
# Criando dois Arrays...
array17 = np.array([1,2,3])
array18 = np.array([3,2,1])

# Soma dos arrays
array19 = np.add(array17, array18)
print(array19)

[4 4 4]


In [106]:
# Para multiplicar duas matrizes numpy, podemos fazer com a função dot()
array20 = np.dot(array17, array18)
print(array20)

10


Para podermos multiplicar duas matrizes, o número de colunas da primeira, tem que ser igual ao número de linhas da segunda.

# FIM