# Aula 15 - Algoritmos e Estrutura de Dados 
## Exercícios sobre Numpy

## Fácil

⚫1- Importe numpy como ‘np’ e imprima o número da versão.

In [11]:
import numpy as np

In [12]:
np.__version__

'1.26.4'

⚫2- Crie uma matriz 1D com números de 0 a 9

In [39]:
arr = np.arange(10)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


⚫3- Crie uma matriz booleana numpy 3×3 com ‘True’

In [40]:
print(np.full((3, 3), True, dtype=bool))

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


⚫4- Extraia todos os números ímpares de ‘arr’

In [54]:
arr = np.arange(10)
impar = arr[arr % 2 == 1]
print(impar)

[1 3 5 7 9]


⚫5- Substitua todos os números ímpares arr por -1

In [60]:
arr[impar] = -1
print(arr)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


## Médio

⚫1- Substitua todos os números ímpares em arr com -1 sem alterar arr

In [65]:
arr = np.arange(10)
out = np.where(arr % 2 == 1, -1, arr)

print(arr)
print(out)


[0 1 2 3 4 5 6 7 8 9]
[ 0 -1  2 -1  4 -1  6 -1  8 -1]


⚫2- Converta uma matriz 1D para uma matriz 2D com 2 linhas:

⚫3- Empilhe matrizes verticalmente:

⚫4- Empilhe as matrizes horizontalmente:

⚫5- Crie o seguinte padrão sem codificação, usando apenas funções numpy e a matriz de entrada abaixo ‘a’.

In [ ]:
a = np.array([1,2,3])

## Difícil 

⚫1- Calcule as contagens de valores únicos na linha.

In [ ]:
import numpy as np
np.random.seed(100)
arr = np.random.randint(1,11,size=(6, 10))
print(arr)

In [ ]:
def counts_of_all_values_rowwise(arr2d):
